package codigo;

import java.util.Random;

/**
 * Programa de lanzamiento de dados para juegos de roll. Este programa permite
 * realizar hasta 100 tiradas con un dado del tipo elejido, hay 7 tipos de dado,
 * entre los que se incluye la moneda.
 *
 * @author Alejandro Luna Gómez
 */
public class Dados extends javax.swing.JFrame {

    /* ----------------------------- Variables ------------------------------ */
    int clicks = 0;
    int saltoLinea = 20;

    /* ------------------------------ Métodos ------------------------------- */
    /**
     * Realiza el lanzamiento de los dados, dependiendo del tipo y cantidad.
     */
    private void lanzaDado() {
        Random r = new Random();
        int numTipoDado = 0;
        int contadorTotal = 0;
        boolean modoMoneda = false;

        int numLanzamientos = (Integer) spinnerLanzamientos.getValue();
        //System.out.println("Número de lanzamientos: " + String.valueOf(numLanzamientos));

        String tipoDado = cajaTipoDado.getSelectedItem().toString();
        //System.out.println("Tipo de dado: " + tipoDado);

        textoResultado.setText(null);

        // Switch del tipo de dado
        switch (tipoDado) {
            case "Moneda":
                numTipoDado = 2;
                modoMoneda = true;
                spinnerLanzamientos.setValue(1);
                break;

            case "D3":
                numTipoDado = 3;
                saltoLinea = 20;
                break;

            case "D4":
                numTipoDado = 4;
                saltoLinea = 20;
                break;

            case "D6":
                numTipoDado = 6;
                saltoLinea = 20;
                break;

            case "D8":
                numTipoDado = 8;
                saltoLinea = 20;
                break;

            case "D10":
                numTipoDado = 10;
                saltoLinea = 15;
                break;

            case "D12":
                numTipoDado = 12;
                saltoLinea = 14;
                break;

            case "D20":
                numTipoDado = 20;
                saltoLinea = 13;
                break;

            case "D100":
                numTipoDado = 100;
                saltoLinea = 12;
                break;

            default:
                numTipoDado = 6;
        }

        // Bucle del número de lanzamientos
        for (int i = 0; i < numLanzamientos; i++) {
            int resultado = 0;
            resultado = r.nextInt(numTipoDado) + 1;
            //System.out.println(String.valueOf(resultado));

            // Si es un lanzamiento de moneda
            if (modoMoneda) {
                switch (resultado) {
                    case 1:
                        textoResultado.setText("Cara");
                        textoSumResultado.setText("Cara");
                        break;

                    case 2:
                        textoResultado.setText("Cruz");
                        textoSumResultado.setText("Cruz");
                        break;

                    default:
                        textoResultado.setText("Error");
                        textoSumResultado.setText("Error");
                }
            } else { // Si el lanzamiento no es de moneda
                // Inserción de retorno de carro a los 23 números
                if (i > 0 && i % saltoLinea == 0) {
                    textoResultado.setText(textoResultado.getText() + "\n");
                }

                // Si el lanzamiento actual del bucle no es el último
                if (i < numLanzamientos - 1) {
                    // Si el texto del resultado está vacio
                    if (textoResultado.getText() == null) {
                        textoResultado.setText(String.valueOf(resultado) + ", ");
                    } else { // Si el resultado tiene algún contenido
                        textoResultado.setText(textoResultado.getText() + String.valueOf(resultado) + ", ");
                    }
                } else { // Si el lanzamiento actual del bucle es el último
                    textoResultado.setText(textoResultado.getText() + String.valueOf(resultado));
                }

                contadorTotal += resultado;
                textoSumResultado.setText(String.valueOf(contadorTotal));
            }
        }
        clicks++;
        textoNumClicks.setText(String.valueOf(clicks));
    }

    ////////////////////////////////////////////////////////////////////////////
    /**
     * Creates new form Dados
     */
    public Dados() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        labelLanzamientos = new javax.swing.JLabel();
        spinnerLanzamientos = new javax.swing.JSpinner();
        labelTipoDado = new javax.swing.JLabel();
        scrollTextoResultado = new javax.swing.JScrollPane();
        textoResultado = new javax.swing.JTextArea();
        cajaTipoDado = new javax.swing.JComboBox<>();
        labelResultado = new javax.swing.JLabel();
        labelSumResultado = new javax.swing.JLabel();
        textoSumResultado = new javax.swing.JTextField();
        botonLanzar = new javax.swing.JButton();
        botonCerrar = new javax.swing.JButton();
        labelNumClicks = new javax.swing.JLabel();
        textoNumClicks = new javax.swing.JLabel();

        jTextField1.setText("jTextField1");

        setResizable(false);

        labelLanzamientos.setText("Lanzamientos:");

        spinnerLanzamientos.setModel(new javax.swing.SpinnerNumberModel(1, 1, 100, 1));

        labelTipoDado.setText("Tipo de dado:");

        textoResultado.setColumns(20);
        textoResultado.setRows(2);
        textoResultado.setEditable(false);
        scrollTextoResultado.setViewportView(textoResultado);

        cajaTipoDado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Moneda", "D3", "D4", "D6", "D8", "D10", "D12", "D20", "D100" }));
        cajaTipoDado.setToolTipText("");

        labelResultado.setText("Resultados:");

        labelSumResultado.setText("Suma resultados:");

        textoSumResultado.setEditable(false);

        botonLanzar.setText("Lanzar");
        botonLanzar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonLanzarMouseClicked(evt);
            }
        });

        botonCerrar.setText("Cerrar");
        botonCerrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonCerrarMouseClicked(evt);
            }
        });

        labelNumClicks.setText("Numero de clicks:");

        textoNumClicks.setText("0");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(scrollTextoResultado, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(labelLanzamientos)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(spinnerLanzamientos, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(labelTipoDado)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cajaTipoDado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(labelResultado)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(botonCerrar)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(labelSumResultado)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(textoSumResultado, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(labelNumClicks)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(textoNumClicks)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(botonLanzar)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(spinnerLanzamientos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelLanzamientos)
                    .addComponent(labelTipoDado)
                    .addComponent(cajaTipoDado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(labelResultado)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(scrollTextoResultado, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelSumResultado)
                    .addComponent(textoSumResultado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(botonLanzar, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(textoNumClicks, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(botonCerrar)
                        .addComponent(labelNumClicks)))
                .addGap(12, 12, 12))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonCerrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonCerrarMouseClicked
        // Cierre de ventana, sin terminar el programa entero
        this.setVisible(false);

        //Cierre temporal hasta incorporar al programa completo
        System.exit(0);
    }//GEN-LAST:event_botonCerrarMouseClicked

    private void botonLanzarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonLanzarMouseClicked
        // Ejecuta el metodo de lanzamiendo de dados.
        lanzaDado();
    }//GEN-LAST:event_botonLanzarMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Dados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Dados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Dados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Dados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Dados().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonCerrar;
    private javax.swing.JButton botonLanzar;
    private javax.swing.JComboBox<String> cajaTipoDado;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel labelLanzamientos;
    private javax.swing.JLabel labelNumClicks;
    private javax.swing.JLabel labelResultado;
    private javax.swing.JLabel labelSumResultado;
    private javax.swing.JLabel labelTipoDado;
    private javax.swing.JScrollPane scrollTextoResultado;
    private javax.swing.JSpinner spinnerLanzamientos;
    private javax.swing.JLabel textoNumClicks;
    private javax.swing.JTextArea textoResultado;
    private javax.swing.JTextField textoSumResultado;
    // End of variables declaration//GEN-END:variables
}
